name: Masscan Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install masscan
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan
          
      - name: Run masscan with sudo
        run: |
          sudo masscan -iL VN-suip.biz.txt \
            -p443 \
            --rate 500000 \
            --wait 15 \
            -oL sobig.txt \
            --status 10 \
            --exclude 255.255.255.255 \
            2>&1 | tee output.log
      - name: Run masscan with sud0
        run: |
          sudo masscan -iL VN-suip.biz.txt \
            -p80 \
            --rate 500000 \
            --wait 15 \
            -oL sobig.txt \
            --status 10 \
            --exclude 255.255.255.255 \
            2>&1 | tee output.log
          
      - name: Fix permission for output files
        run: |
          sudo chown $USER:$USER sobig.txt output.log 2>/dev/null || true
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: |
            sobig.txt
            output.log
